name: Reusable Workflow
on:
  workflow_call:
    inputs:
      src-folder:
        description: 'Source folder of the calling repository'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      src-folder:
        description: 'Source folder of the calling repository'
        required: true
        type: string
permissions:
  contents: "read"
  id-token: "write"
  actions:  "read"
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Print Source Folder Path
        run: echo "Source Folder Path ${{ inputs.src-folder }}"
      - name: Debug Repository Structure
        run: ls -R ${{ github.workspace }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run Python script
        env:
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}  # Pass the secret to the script
          SRC_FOLDER: ${{ inputs.src-folder}}
        run: |
          python generate_doc.py
