name: Reusable Workflow
on:
  workflow_call:
    inputs:
      src-folder:
        description: 'Source folder of the calling repository'
        required: true
        type: string
      repo-name:
        description: 'Name of the calling repository'
        required: true
        type: string
      branch-name:
        description: 'Branch of the calling repository'
        required: true
        type: string
      token:
        required: true
        type: string  # Ensure token is defined as a string
  workflow_dispatch:
    inputs:
      src-folder:
        description: 'Source folder of the calling repository'
        required: true
        type: string
      repo-name:
        description: 'Name of the calling repository'
        required: true
        type: string
      branch-name:
        description: 'Branch of the calling repository'
        required: true
        type: string
      token:
        required: true
        type: string  # Ensure token is defined as a string
permissions:
  contents: "read"
  id-token: "write"
  actions:  "read"
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Caller Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repo-name }}
          ref: ${{ inputs.branch-name }}
          token: ${{ inputs.token }}
          path: repo-caller
      - name: Checkout Callee Repository
        uses: actions/checkout@v4
        with:
          token: ${{ inputs.token }}
          path: repo-callee
      - name: Print Source Folder Path
        run: echo "Source Folder Path ${{ inputs.src-folder }}"

      - name: Debug Repository Structure
        run: ls -R ${{ github.workspace }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install -r repo-callee/requirements.txt
      - name: Run Python script
        env:
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}  # Pass the secret to the script
          SRC_FOLDER: ${{ github.workspace }}/repo-caller/${{ inputs.src-folder}}
        run: |
          python repo-callee/generate_doc.py
